### ISSUE TITLE
Issue when launch cloudfomation stack

### ISSUE THREAD

**Issue by taoshen-amazon** [aws-samples/amazon-sagemaker-predictive-maintenance-deployed-at-edge#1]
when I launch the cloudfomation template, it failed for creation of IoTWSSageMakerInstance with following status reason:
"fatal: could not read Username for 'https://github.com/stefannatu/IOT-ML-Workshop': terminal prompts disabled"
what could be the reason for this and how can I deal with it? Thanks!

**Comment by stefannatu** [comment]
@taoshen-amazon Thanks so much for your interest in this workshop, and apologies for the delay in response. It should be resolved now, there was an issue with the Github repo that the cloudformation template was trying to reference. Please let me know if you have any other issues and if this step works.

**Comment by stefannatu** [comment]
@taoshen-amazon Thanks so much for your interest in this workshop, and apologies for the delay in response. It should be resolved now, there was an issue with the Github repo that the cloudformation template was trying to reference. Please let me know if you have any other issues and if this step works.
