### ISSUE TITLE
failed to initialize with reason Installed Java version must be greater than or equal to 8

### ISSUE THREAD

**Issue by collinarnett** [aws-samples/amazon-sagemaker-predictive-maintenance-deployed-at-edge#10]
I get this error when trying to deploy to virtual sensor. Did I miss a step or is this not included in the tutorial?

**Comment by collinarnett** [comment]
After installing Amazon Corretto 8 by using the following commands: 
```
wget https://corretto.aws/downloads/latest/amazon-corretto-8-x64-linux-jdk.rpm
sudo yum localinstall amazon-corretto*.rpm
```
the issue was resolved. I would add a PR for this but I'm not sure where to put this in the documentation or if this does not warrant a PR or is just my negligence in the installation process.

**Comment by stefannatu** [comment]
Hi collinarnett, this is also resolved now in the setup .sh script, we have included Java 8 installation.
