### ISSUE TITLE
The CFT is not public and it cannot be accessed

### ISSUE THREAD

**Issue by catavie** [aws-samples/amazon-sagemaker-predictive-maintenance-deployed-at-edge#3]
https://iot-ml-predictive-maintenance.s3.amazonaws.com/iot-ml-predictive-maintenance.json

Can you please add the json CFT file above to the code section?

**Comment by stefannatu** [comment]
This should now be fixed. Can you please check?

**Comment by catavie** [comment]
Yes, it works now. Thanks!
